# Generated by Django 5.2.8 on 2025-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
