# Generated by Django 5.2.8 on 2025-11-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_assignment_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='color',
            field=models.CharField(default='#4a90e2', max_length=7),
        ),
    ]
