# Generated by Django 5.2.8 on 2025-11-26 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_classroom_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='color',
        ),
        migrations.AddField(
            model_name='classroom',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='class_banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='classroom',
            name='gradient_end',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='classroom',
            name='gradient_start',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
