# Generated by Django 5.2.8 on 2025-12-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_classroom_color_classroom_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_past',
            field=models.BooleanField(default=False),
        ),
    ]
