# Generated by Django 5.2.8 on 2025-12-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assignment_is_past'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_past',
        ),
    ]
